In [276]:
import pandas as pd
import os

In [296]:
# Existentes
plusvalias = {}
regiones = [archivo for archivo in os.listdir('db/Plusvalias') if "xlsx" in archivo and "extra" not in archivo]
for region in regiones:
    archivo_region = f"db/Plusvalias/{region}"
    datos = pd.ExcelFile(archivo_region)
    for comuna in datos.sheet_names:
        comuna_df = pd.read_excel(archivo_region, sheet_name=comuna)
        comuna_df = comuna_df[comuna_df['UF/m2'] != '-']
        plusvalia =  comuna_df.tail(1).loc[:,'UF/m2'].item()/comuna_df.head(1).loc[:,'UF/m2'].item()
        semestres = int(comuna_df.tail(1).loc[:,'Semestre'].item()[-2:]) -  int(comuna_df.head(1).loc[:,'Semestre'].item()[-2:])
        plusvalias[comuna] = f"%{100*(plusvalia**(1/semestres)-1):.2f}"

plusvalias

{'Temuco': '%0.38',
 'BioBio': '%5.74',
 'La Florida': '%8.06',
 'Macul': '%9.00',
 'Nunoa': '%7.50',
 'La Cisterna': '%8.16',
 'Santiago': '%7.70',
 'Coquimbo': '%2.73',
 'Valparaiso': '%4.64'}

In [289]:
inicio = 2018
fin = 2023
df_comunas = pd.read_excel('db/Plusvalias/Plusvalias_extra.xlsx')
df_comunas['Plusvalia'] = df_comunas.apply(lambda row: f"%{100*((row[fin]/row[inicio])**(1/(fin-inicio))-1):.2f}", axis=1)
df_comunas.sort_values(by='Comuna')

,Comuna,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Plusvalia
2,Estacion Central,1564,1526,1750,1738,1856,2084,2098,2162,2257,2381,2341,%5.11
6,Independencia,1430,1658,1936,1845,1903,2594,2439,2718,2798,2821,3120,%8.19
7,La Cisterna,1555,1748,1743,1882,1908,2169,2379,2462,2553,2559,2444,%6.05
4,La Florida,1972,2123,2333,2692,2841,3074,3088,3275,3289,3140,3150,%2.02
8,Las Condes,7339,6769,7131,8318,8684,8841,10202,9653,9464,9688,7813,%2.21
12,Lo Barnechea,12487,12253,11492,11027,11186,11484,11934,11910,12517,12184,12436,%1.72
5,Macul,2301,2282,2545,2735,2853,3039,3235,3385,3478,3557,3644,%4.51
13,Maipu,1823,2116,2427,2615,2869,3129,3305,3574,3590,3682,3523,%5.12
1,Nunoa,3472,3695,3848,4229,4146,4418,4336,4494,4189,3946,3903,%-0.98
9,Providencia,6086,7030,7200,7237,8068,8107,8107,8149,8692,8633,8311,%1.36
10,Quinta Normal,1213,1441,1443,1659,1848,2105,2134,2439,2562,2635,2782,%7.35
14,San Joaquin,1635,1913,1764,2178,2614,3061,2985,2824,3013,2938,2749,%2.36
3,San Miguel,2198,2408,2264,2317,2490,2728,2900,3136,2818,3200,3102,%5.15
0,Santiago,1853,2085,2243,2435,2578,2821,2885,2925,2878,2926,2991,%2.56
11,Vitacura,13701,12628,11675,12764,11762,12450,12443,13499,13692,15274,13495,%5.36

In [297]:
# Entender que comunas no tienen registros
for region in sorted(os.listdir('db/Proyectos')):
    if "DS" in region: continue
    for comuna in sorted(os.listdir(f'db/Proyectos/{region}')):
        if "xlsx" in comuna:
            comuna = comuna.split("_")[0]
            if comuna in plusvalias.keys():
                print(comuna, "Diccionario")
                print(plusvalias[comuna])
            elif comuna in df_comunas['Comuna'].unique():
                print(comuna, "Dataframe")
                print(df_comunas.loc[df_comunas['Comuna'] == comuna, "Plusvalia"].item())
            else:
                print(comuna, 'No existe')
                print("%2")

Antofagasta No existe
%2
Calama No existe
%2
Concepcion No existe
%2
Los Angeles No existe
%2
Talcahuano No existe
%2
Coquimbo Diccionario
%2.73
La Serena No existe
%2
Pucon No existe
%2
Temuco Diccionario
%0.38
Osorno No existe
%2
Puerto Montt No existe
%2
Puerto Varas No existe
%2
Valdivia No existe
%2
Chillan No existe
%2
Rancagua No existe
%2
Cerrillos No existe
%2
Conchali No existe
%2
Estacion Central Dataframe
%5.11
Huechuraba No existe
%2
Independencia Dataframe
%8.19
La Cisterna Diccionario
%8.16
La Florida Diccionario
%8.06
La Reina No existe
%2
Las Condes Dataframe
%2.21
Lo Barnechea Dataframe
%1.72
Macul Diccionario
%9.00
Maipu Dataframe
%5.12
Nunoa Diccionario
%7.50
Providencia Dataframe
%1.36
Quinta Normal Dataframe
%7.35
Recoleta No existe
%2
San Joaquin Dataframe
%2.36
San Miguel Dataframe
%5.15
Santiago Diccionario
%7.70
Vitacura Dataframe
%5.36
Concon No existe
%2
Valparaiso Diccionario
%4.64
Viña Del Mar No existe
%2